/**
 * EZIHE SUPER BOT - AI Handler
 * Handles AI image generation, video generation, and chat
 */

const axios = require('axios');
const fs = require('fs-extra');
const path = require('path');
const FormData = require('form-data');
const logger = require('../utils/logger');
const database = require('../utils/database');
const config = require('../config/config');

// Active generations tracker
const activeGenerations = new Map();

/**
 * AI Image Generation Command
 */
async function imageCommand(ctx) {
  const args = ctx.message.text.split(' ').slice(1);
  
  if (args.length === 0) {
    return ctx.reply(`
🖼️ <b>AI Image Generator</b>

Create stunning images from text descriptions!

<b>Usage:</b>
/aiimg [your description]

<b>Examples:</b>
/aiimg a beautiful sunset over mountains
/aiimg futuristic cyberpunk city at night
/aiimg cute cat wearing astronaut helmet

<b>Tips:</b>
• Be descriptive for better results
• Include style keywords (digital art, realistic, anime)
• Mention lighting and mood
`, { parse_mode: 'HTML' });
  }

  const prompt = args.join(' ');
  await generateImage(ctx, prompt);
}

/**
 * Generate AI Image
 */
async function generateImage(ctx, prompt) {
  const userId = ctx.from.id;

  try {
    // Check if already generating
    if (activeGenerations.has(userId)) {
      return ctx.reply('⏳ You already have an active generation. Please wait...');
    }

    activeGenerations.set(userId, true);

    const processingMsg = await ctx.reply(`
🎨 <b>Generating Image...</b>

📝 Prompt: <i>${prompt.substring(0, 100)}${prompt.length > 100 ? '...' : ''}</i>

⏳ This may take 10-30 seconds...
`, { parse_mode: 'HTML' });

    let imageUrl = null;
    let imageBuffer = null;

    // Try multiple AI image APIs
    
    // Method 1: Pollinations AI (Free, no API key)
    try {
      const encodedPrompt = encodeURIComponent(prompt);
      imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=1024&height=1024&nologo=true`;
      
      const response = await axios.get(imageUrl, {
        responseType: 'arraybuffer',
        timeout: 60000,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
      });
      
      imageBuffer = Buffer.from(response.data);
    } catch (err) {
      logger.warn('Pollinations AI failed, trying fallback...');
    }

    // Method 2: Stable Diffusion API (if key available)
    if (!imageBuffer && config.apiKeys.stability) {
      try {
        const response = await axios.post(
          'https://api.stability.ai/v2beta/stable-image/generate/sd3',
          {
            prompt: prompt,
            output_format: 'jpeg',
            aspect_ratio: '1:1'
          },
          {
            headers: {
              'Authorization': `Bearer ${config.apiKeys.stability}`,
              'Content-Type': 'application/json'
            },
            responseType: 'arraybuffer',
            timeout: 60000
          }
        );
        imageBuffer = Buffer.from(response.data);
      } catch (err) {
        logger.warn('Stability API failed:', err.message);
      }
    }

    // Method 3: Hugging Face (Free tier)
    if (!imageBuffer) {
      try {
        const response = await axios.post(
          'https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0',
          { inputs: prompt },
          {
            headers: {
              'Authorization': `Bearer ${config.apiKeys.huggingface || 'hf_demo'}`,
              'Content-Type': 'application/json'
            },
            responseType: 'arraybuffer',
            timeout: 120000
          }
        );
        imageBuffer = Buffer.from(response.data);
      } catch (err) {
        logger.warn('Hugging Face API failed:', err.message);
      }
    }

    if (!imageBuffer) {
      throw new Error('All image generation services failed');
    }

    // Save temporary file
    const tempDir = path.join(config.paths.temp, `ai_img_${userId}`);
    await fs.ensureDir(tempDir);
    const filePath = path.join(tempDir, `generated_${Date.now()}.jpg`);
    await fs.writeFile(filePath, imageBuffer);

    // Delete processing message
    await ctx.telegram.deleteMessage(processingMsg.chat.id, processingMsg.message_id);

    // Send generated image
    await ctx.replyWithPhoto(
      { source: filePath },
      {
        caption: `
🖼️ <b>AI Generated Image</b>

📝 Prompt: <i>${prompt}</i>

✨ Generated by EZIHE BOT AI
`,
        parse_mode: 'HTML'
      }
    );

    // Log generation
    await database.logAIGeneration(userId, 'image', prompt, imageUrl || 'generated');

    // Cleanup
    await fs.remove(filePath);
    activeGenerations.delete(userId);

  } catch (error) {
    logger.error('AI image generation error:', error);
    activeGenerations.delete(userId);
    ctx.reply(`
❌ <b>Image Generation Failed</b>

Error: ${error.message}

Please try again with a different prompt.
`, { parse_mode: 'HTML' });
  }
}

/**
 * AI Video Generation Command
 */
async function videoCommand(ctx) {
  const args = ctx.message.text.split(' ').slice(1);
  
  if (args.length === 0) {
    return ctx.reply(`
🎥 <b>AI Video Generator</b>

Create amazing videos from text descriptions!

<b>Usage:</b>
/aivid [your description]

<b>Examples:</b>
/aivid a serene forest with sunlight filtering through trees
/aivid ocean waves crashing on a tropical beach
/aivid futuristic city with flying cars at sunset

<b>Note:</b>
• Video generation takes 1-3 minutes
• Results are 4-10 seconds long
• Be descriptive for best results
`, { parse_mode: 'HTML' });
  }

  const prompt = args.join(' ');
  await generateVideo(ctx, prompt);
}

/**
 * Generate AI Video
 */
async function generateVideo(ctx, prompt) {
  const userId = ctx.from.id;

  try {
    if (activeGenerations.has(userId)) {
      return ctx.reply('⏳ You already have an active generation. Please wait...');
    }

    activeGenerations.set(userId, true);

    const processingMsg = await ctx.reply(`
🎬 <b>Generating Video...</b>

📝 Prompt: <i>${prompt.substring(0, 100)}${prompt.length > 100 ? '...' : ''}</i>

⏳ This may take 1-3 minutes...
Please be patient!
`, { parse_mode: 'HTML' });

    let videoUrl = null;
    let videoBuffer = null;

    // Method 1: Using Runway ML API (if key available)
    if (config.apiKeys.runway) {
      try {
        // Runway API implementation would go here
        // This is a placeholder for the actual implementation
        throw new Error('Runway API not implemented');
      } catch (err) {
        logger.warn('Runway API failed:', err.message);
      }
    }

    // Method 2: Using free video generation API
    if (!videoBuffer) {
      try {
        // Using a free video generation service
        const apiUrl = `https://api.pika.art/generate`;
        
        const response = await axios.post(apiUrl, {
          prompt: prompt,
          duration: 4,
          aspect_ratio: '16:9'
        }, {
          timeout: 180000,
          headers: {
            'Content-Type': 'application/json'
          }
        });

        if (response.data && response.data.video_url) {
          videoUrl = response.data.video_url;
          const videoResponse = await axios.get(videoUrl, {
            responseType: 'arraybuffer',
            timeout: 60000
          });
          videoBuffer = Buffer.from(videoResponse.data);
        }
      } catch (err) {
        logger.warn('Pika API failed:', err.message);
      }
    }

    // Method 3: Fallback to image sequence or animated GIF
    if (!videoBuffer) {
      // Generate multiple images and create a simple animation
      await ctx.telegram.editMessageText(
        processingMsg.chat.id,
        processingMsg.message_id,
        null,
        '🎬 Using alternative method... Generating animated content'
      );

      try {
        // Generate an animated GIF using Pollinations
        const encodedPrompt = encodeURIComponent(prompt + ', animated, motion');
        const gifUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=512&height=512&nologo=true&seed=${Date.now()}`;
        
        const response = await axios.get(gifUrl, {
          responseType: 'arraybuffer',
          timeout: 60000
        });
        
        videoBuffer = Buffer.from(response.data);
      } catch (err) {
        throw new Error('Video generation services unavailable');
      }
    }

    if (!videoBuffer) {
      throw new Error('Failed to generate video');
    }

    // Save temporary file
    const tempDir = path.join(config.paths.temp, `ai_vid_${userId}`);
    await fs.ensureDir(tempDir);
    const filePath = path.join(tempDir, `generated_${Date.now()}.mp4`);
    await fs.writeFile(filePath, videoBuffer);

    // Delete processing message
    await ctx.telegram.deleteMessage(processingMsg.chat.id, processingMsg.message_id);

    // Send generated video
    await ctx.replyWithVideo(
      { source: filePath },
      {
        caption: `
🎥 <b>AI Generated Video</b>

📝 Prompt: <i>${prompt}</i>

✨ Generated by EZIHE BOT AI
`,
        parse_mode: 'HTML',
        supports_streaming: true
      }
    );

    // Log generation
    await database.logAIGeneration(userId, 'video', prompt, videoUrl || 'generated');

    // Cleanup
    await fs.remove(filePath);
    activeGenerations.delete(userId);

  } catch (error) {
    logger.error('AI video generation error:', error);
    activeGenerations.delete(userId);
    
    ctx.reply(`
❌ <b>Video Generation Failed</b>

Error: ${error.message}

The video generation service may be temporarily unavailable.
Please try again later or use /aiimg to generate images instead.
`, { parse_mode: 'HTML' });
  }
}

/**
 * AI Chat Command
 */
async function chatCommand(ctx) {
  const args = ctx.message.text.split(' ').slice(1);
  
  if (args.length === 0) {
    return ctx.reply(`
💬 <b>AI Chat</b>

Chat with an intelligent AI assistant!

<b>Usage:</b>
/ai [your message]

<b>Examples:</b>
/ai What is the weather like today?
/ai Explain quantum physics simply
/ai Write a poem about nature
/ai Help me code a Python function

<b>Features:</b>
• Answer questions
• Help with coding
• Creative writing
• Explain concepts
• And much more!
`, { parse_mode: 'HTML' });
  }

  const message = args.join(' ');
  await chatWithAI(ctx, message);
}

/**
 * Chat with AI
 */
async function chatWithAI(ctx, message) {
  const userId = ctx.from.id;

  try {
    const processingMsg = await ctx.reply('🤔 Thinking...');

    let response = null;

    // Method 1: OpenAI API (if key available)
    if (config.apiKeys.openai) {
      try {
        const result = await axios.post(
          'https://api.openai.com/v1/chat/completions',
          {
            model: 'gpt-3.5-turbo',
            messages: [
              { role: 'system', content: 'You are a helpful assistant.' },
              { role: 'user', content: message }
            ],
            max_tokens: 1000
          },
          {
            headers: {
              'Authorization': `Bearer ${config.apiKeys.openai}`,
              'Content-Type': 'application/json'
            },
            timeout: 30000
          }
        );
        response = result.data.choices[0].message.content;
      } catch (err) {
        logger.warn('OpenAI API failed:', err.message);
      }
    }

    // Method 2: Free AI API (Hugging Face or similar)
    if (!response) {
      try {
        const result = await axios.post(
          'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2',
          { inputs: `<s>[INST] ${message} [/INST]` },
          {
            headers: {
              'Content-Type': 'application/json'
            },
            timeout: 30000
          }
        );
        
        if (result.data && result.data[0]) {
          response = result.data[0].generated_text;
          // Clean up the response
          response = response.replace(/<s>\[INST\].*?\[\/INST\]\s*/, '').trim();
        }
      } catch (err) {
        logger.warn('Hugging Face API failed:', err.message);
      }
    }

    // Method 3: Simple response fallback
    if (!response) {
      response = `I received your message: "${message}"\n\nNote: AI services are currently unavailable. Please try again later or contact the bot owner to configure API keys.`;
    }

    // Delete processing message
    await ctx.telegram.deleteMessage(processingMsg.chat.id, processingMsg.message_id);

    // Send response (split if too long)
    const maxLength = 4000;
    if (response.length > maxLength) {
      const chunks = response.match(new RegExp(`.{1,${maxLength}}`, 'g'));
      for (const chunk of chunks) {
        await ctx.reply(chunk, { parse_mode: 'HTML' });
      }
    } else {
      await ctx.reply(response, { parse_mode: 'HTML' });
    }

  } catch (error) {
    logger.error('AI chat error:', error);
    ctx.reply('❌ Sorry, I encountered an error. Please try again later.');
  }
}

/**
 * AI Action Handler
 */
async function aiAction(ctx) {
  const action = ctx.match[1];
  
  switch (action) {
    case 'image':
      await ctx.answerCbQuery('Use /aiimg command');
      await ctx.reply('Use the command: /aiimg [your prompt]');
      break;
    case 'video':
      await ctx.answerCbQuery('Use /aivid command');
      await ctx.reply('Use the command: /aivid [your prompt]');
      break;
    case 'chat':
      await ctx.answerCbQuery('Use /ai command');
      await ctx.reply('Use the command: /ai [your message]');
      break;
    case 'styles':
      await ctx.reply(`
🎨 <b>AI Art Styles</b>

Try these style keywords in your prompts:

• <b>Digital Art</b> - "digital art style"
• <b>Realistic</b> - "photorealistic, 8k"
• <b>Anime</b> - "anime style, manga"
• <b>Oil Painting</b> - "oil painting, classical"
• <b>Watercolor</b> - "watercolor painting"
• <b>Cyberpunk</b> - "cyberpunk, neon lights"
• <b>Fantasy</b> - "fantasy art, magical"
• <b>3D Render</b> - "3D render, blender"

<b>Example:</b>
/aiimg a cyberpunk city at night, neon lights, digital art style
`);
      break;
    default:
      await ctx.answerCbQuery('Unknown action');
  }
}

module.exports = {
  imageCommand,
  videoCommand,
  chatCommand,
  generateImage,
  generateVideo,
  chatWithAI,
  aiAction
};
